name: Build Vehicle Data Set
on: push
jobs:
  Build-Vehicle-Data-Set:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Build Vehicle Data Set
        run: |
          python build/build.py
      - name: Commit Vehicle Data Set
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Build Vehicle Data Set `date`"
          git diff-index --quiet HEAD
          [[ $? -eq 0 ]] && exit 0
          git push