name: Build Vehicle Data Set
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Aggregate file
        run: date +%s > vehicle/all.txt
      - name: Commit report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Build Vehicle Data Set `date`"
          git push