name: Build Vehicle Data Set
on: push
jobs:
  Build-Vehicle-Data-Set:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Build Vehicle Data Set
        run: |
          python build/build.py
      - name: Commit Vehicle Data Set
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git status | grep modified
          if [ $? -eq 0 ]
          then
            git add --all
            git commit -am "Build Vehicle Data Set `date`"
            git push
          else
            echo "No updates for the vehicle data store"
          fi