name: Build Vehicle Data Set
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Vehicle Data Set
        run: |
          ls -l vehicle/r*json > vehicle/motorcycles.json
      - name: Commit Vehicle Data Set
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -am "Build Vehicle Data Set `date`"
          git push